FROM ubuntu:latest

RUN apt-get update && apt-get install -y gcc make libc6-dev libpq-dev postgresql

COPY *.c /app/
COPY *.h /app/
WORKDIR /app

RUN gcc -o server *.c -lpq

EXPOSE 8081

CMD ["./server"]